version: 1

translation_target: "FR"

goose_config:
  browser_user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2)"
  enable_image_fetching: False
  keep_footnotes: True
  parse_headers: True
  strict: True

openai_config:
  image_size: "512x512"
  completions_engine: "text-davinci-003"
  prompts:
    summarize:
      prompt: "As an expert in synthesizing information, summarize the key 
      points and main arguments made in the following article in 300 words 
      or less. Additionally, provide an honest evaluation of the article in 
      one sentence, incorporating any relevant knowledge or insights from your 
      training data. 
      Article : {text}"
      max_tokens: 300
      temperature: 0.3
    generate_instructions:
      prompt: "Write a set of clear and detailed instructions for creating an 
      illustration for the following article summary. The instructions should outline 
      the desired art style, themes, and content of the illustration, and 
      should include any specific ideas or concepts that should be depicted 
      in the image. The instructions should also consider the appropriateness 
      and safety of the content, and should avoid any potentially harmful or 
      triggering themes or images. The output should not contain text.
      Summary : {text}"
      max_tokens: 150
      temperature: 0.1
    generate_title:
      prompt: "Generate a catchy and informative title for the following 
      article summary, incorporating key themes and ideas from the text. The title should 
      be concise and attention-grabbing, ideally no more than 10 words in length.
      Summary : {text}"
      max_tokens: 20
      temperature: 0.7