import os

import openai


def get_completion(
    model: str, context: str, template_prompt: str, temp: float, max_t: float
):
    """
    This function uses the OpenAI API to generate a completion for a given
    prompt. The prompt is generated by inserting the value of context
    into the template_prompt string. The temperature and maximum number of
    tokens can be controlled through the temp and max_t arguments, respectively.
    The model argument specifies which OpenAI model to use for generating the
    completion. The function returns the generated completion as a string.
    """
    openai.api_key = os.environ["OPENAI_API_KEY"]
    formatted_prompt = template_prompt.format(text=context)
    completions = openai.Completion.create(
        engine=model,
        prompt=formatted_prompt,
        max_tokens=max_t,
        n=1,
        temperature=temp,
        top_p=1,
    )
    completion = completions.choices[0]
    return completion.text
